ViewModels/AllBussesViewModel.cs
using BussesRouteMiniProject.Data.Models;

namespace BussesRouteMiniProject.ViewModels
{
    public class AllBussesViewModel
    {
        public int Id { get; set; }
        public string Number { get; set; } = null!;

        public List<Stop> Stops { get; set; } = null!;
    }
}

ViewModels/ErrorViewModel.cs
namespace BussesRouteMiniProject.ViewModels
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ViewModels/StopsByBusIdViewModel.cs
namespace BussesRouteMiniProject.ViewModels
{
    public class StopsByBusIdViewModel
    {
        public string Name { get; set; } = null!;
        public string Number { get; set; } = null!;
        public string Location { get; set; } = null!;
        public int BusNumber { get; set; }
    }
}

Controllers/BusController.cs
using BussesRouteMiniProject.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace BussesRouteMiniProject.Controllers
{
    public class BusController : Controller
    {
        private readonly IBusService _busService;

        public BusController(IBusService busService)
        {
            this._busService = busService;
        }
        public async Task<IActionResult> ShowAll()
        {
            var busses = await _busService.GetAllBussesAsync();
            return View(busses);
        }
    }
}

Controllers/HomeController.cs
using BussesRouteMiniProject.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BussesRouteMiniProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/StopController.cs
using BussesRouteMiniProject.Services.Interfaces;
using BussesRouteMiniProject.Services.Services.Models;
using BussesRouteMiniProject.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BussesRouteMiniProject.Controllers
{
    public class StopController : Controller
    {
        private readonly IStopService stopService;

        public StopController(IStopService service)
        {
            stopService = service;
        }
        public async Task<IActionResult> ShowStopsByBusId(int id)
        {
            var stops = await stopService.GetStopsByBusIdAsync(id);

            return View(stops);
        }
        public async Task<IActionResult> ShowRoute([FromQuery]StopsSearchModel model)
        {
            List<AllBussesViewModel> busses = await stopService.GetRouteAsync(model);
            model.Busses = busses;
            return View(model);
        }
    }
}

Views/Bus/ShowAll.cshtml
@model List<AllBussesViewModel>
@{
    ViewBag.Title = "All Busses";
}


<h1>
    All Busses
</h1>
<div class="cards">
    @{
        for (int i = 0; i < Model.Count; i++)
        {
            <div class="card">
                <img src="~/imgs/bus.jpeg" class="card-img-top" alt="bus image">
                <div class="card-body" style="justify-content:center">
                    <h5 class="card-title">@Model[i].Number</h5>
                    <a asp-controller="Stop" asp-action="ShowStopsByBusId" asp-route-id="@Model[i].Id" class="btn btn-primary">See Stops</a>
                </div>
            </div>
        }
    }
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BussesRouteMiniProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BussesRouteMiniProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BussesRouteMiniProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bus" asp-action="ShowAll">Busses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Stop" asp-action="ShowRoute">Route</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BussesRouteMiniProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Stop/ShowRoute.cshtml
@model StopsSearchModel


<form method="get">
    <label asp-for="StartingStop"></label>
    <input asp-for="StartingStop" class="form-control" placeholder="...">

    <label asp-for="FinalStop"></label>
    <input asp-for="FinalStop" class="form-control" placeholder="...">
    <div class="form-group mt-4 p-2">
        <input type="submit" value="Search" class="btn btn-primary" />
    </div>
</form>
@{
    if (Model.Busses.Count == 0)
    {
        <p>No routes found.</p>
    }
    else
    {
        foreach (var bus in Model.Busses)
        {
            <div class="card">
                <img src="~/imgs/bus.jpeg" class="card-img-top" alt="bus image">
                <div class="card-body" style="justify-content:center">
                    <h5 class="card-title">@bus.Number</h5>
                    <p class="showStops">See Stops</p>
                    <div class="routeStops" style="display:none">
                        @{
                            foreach (var stop in bus.Stops)
                            {
                                <p>- @stop.Name</p>
                            }
                        }
                    </div>
                </div>
            </div>
        }
    }
}
<script src="~/js/ShowStopsInRoute.js"></script>
<script src="https://kit.fontawesome.com/6326f1a500.js" crossorigin="anonymous"></script>

Views/Stop/ShowStopsByBusId.cshtml
@model List<StopsByBusIdViewModel>

@{
    ViewBag.Title = "Автобус " + @Model.First().BusNumber;
}

<h1>Автобус @Model.First().BusNumber</h1>
<div class="cards" style="display:block">
    @for (int i = 0; i < Model.Count; i++)
    {
        <div style="width:600px">
            <div class="upperCard">
                @Model[i].Name
                <p class="showAndHide">Покажи още..</p>
            </div>
            <div class="more" style="display:none">
                <iframe src="@Model[i].Location" width="600" height="450" style="border:0; border-radius:5px" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
            @if (i < Model.Count - 1)
            {
                <p style="font-size:100px; text-align:center">&#129035;</p>
            }
        </div>
    }
</div>